from app import db
from models.base import BaseModel


class ResortInfoModel(db.Model, BaseModel):
    __tablename__ = "resort_info"

    name = db.Column(db.Text, nullable=False, unique=True)
    country = db.Column(db.Text)
    continent = db.Column(db.Text)
    latitude = db.Column(db.Text)
    longitude = db.Column(db.Text)
    top_altitude = db.Column(db.Text)
    bottom_altitude = db.Column(db.Text)
    total_vertical = db.Column(db.Text)
    total_pistes = db.Column(db.Text)
    blue_pistes = db.Column(db.Text)
    red_pistes = db.Column(db.Text)
    black_pistes = db.Column(db.Text)
    total_lifts = db.Column(db.Text)
    drag_lifts = db.Column(db.Text)
    chair_lifts = db.Column(db.Text)
    gondola_lifts = db.Column(db.Text)
    skill_level = db.Column(db.Text)
    area = db.Column(db.Text)
    tourist_office_email = db.Column(db.Text)
    tourist_office_phone = db.Column(db.Text)
    season_open = db.Column(db.Text)
    season_close = db.Column(db.Text)
    nearest_airport = db.Column(db.Text)
    nearest_train_station = db.Column(db.Text)
    total_restaurants = db.Column(db.Text)
    total_bars = db.Column(db.Text)
    terrain_parks = db.Column(db.Text)
    cross_country_skiing = db.Column(db.Text)
    piste_condition = db.Column(db.Text)
    off_piste_condition = db.Column(db.Text)
    upper_snow_depth = db.Column(db.Text)
    lower_snow_depth = db.Column(db.Text)
    best_snow_month = db.Column(db.Text)
    average_snow_days_per_week = db.Column(db.Text)
    overall_rating = db.Column(db.Text)
    snowsure_rating = db.Column(db.Text)
    variety_of_pistes_rating = db.Column(db.Text)
    off_piste_rating = db.Column(db.Text)
    scenery_rating = db.Column(db.Text)
    apres_ski_rating = db.Column(db.Text)
