# fly.toml app configuration file generated for resort-info on 2023-06-19T13:18:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "resort-info"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"

[env]


[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
